name: Build Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: "main"
          flutter-version: "3.24.4"

      - name: Build Budgetman
        run: |
          flutter clean
          flutter pub get
          flutter build apk