name: Build and Deploy Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Set Tag Version
        id: tag_version
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: "main"
          flutter-version: "3.24.4"
      
      - name: Run Flutter Unit Test
        run: flutter test test/unit_test.dart
      
      - name: Run Flutter UI Test
        run: flutter test test/ui_test.dart

      # - name: Run Flutter Integration Test
      #   continue-on-error: true
      #   uses: ReactiveCircus/android-emulator-runner@v2
      #   with:
      #     api-level: 29
      #     arch: x86_64
      #     target: google_apis
      #     script: bash ./utils/run.sh

      - name: Build Budgetman
        run: |
          flutter clean
          flutter pub get
          flutter build apk --split-per-abi --obfuscate --split-debug-info build/debug-symbol --build-name ${{ env.TAG_NAME }}
    
      - name: Create Release and Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          name: Budgetman Release v${{ env.TAG_NAME }}
          body: "Release ${{ env.TAG_NAME }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./build/app/outputs/flutter-apk/*
